### ISSUE TITLE
Fails to auth

### ISSUE THREAD

**Issue by NuxRo** [pitpompej/kodi_plugins#3]
Hello,

I've installed your addon on Libreelec (devel , Kodi Leia)
It akss me my Amazon credentials (including 2fa), but then fails with the following.
Any ideas?

13:21:21.315 T:1178661776   ERROR: /storage/.kodi/addons/plugin.audio.prime_music/default.py:585: UserWarning: gzip transfer encoding is experimental!
                                              br.set_handle_gzip(True)
13:21:22.700 T:1178661776   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'mechanize._mechanize.FormNotFoundError'>
                                            Error Contents: no form matching name 'signIn'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.prime_music/default.py", line 858, in <module>
                                                index()
                                              File "/storage/.kodi/addons/plugin.audio.prime_music/default.py", line 84, in index
                                                loginResult = login()
                                              File "/storage/.kodi/addons/plugin.audio.prime_music/default.py", line 589, in login
                                                br.select_form(name="signIn")
                                              File "/storage/.kodi/addons/script.module.mechanize/lib/mechanize/_mechanize.py", line 524, in select_form
                                                raise FormNotFoundError("no form matching "+description)
                                            FormNotFoundError: no form matching name 'signIn'
                                            -->End of Python script error report<--
13:21:22.881 T:1942577168   ERROR: GetDirectory - Error getting plugin://plugin.audio.prime_music/
13:21:22.882 T:1942577168   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.prime_music/) failed

**Comment by NuxRo** [comment]
The Libreelec version is:
 LibreELEC (community): devel-20171108225815-#1108-gadfe87b (RPi2.arm)

**Comment by pitpompej** [comment]
Hi,
have you tried to log in to the amazon music website by using a PC and webbrowser?
somehow it is sometimes only possible to login with this plugin for the first time when you previously logged in to the website with a webbrowser.

**Comment by NuxRo** [comment]
Auth works without problems on their web site, everything looks good.
(though they complain I don't have flash which I refuse to install in 2017).

**Comment by pitpompej** [comment]
ok, that should be fine so far.
you have a german amazon prime account and also selected the german version in the plugin?
and you are using the 2 factor auth for the amazon login?

**Comment by NuxRo** [comment]
I'm using amazon.co.uk and selected it in the preferences.
I managed to login, seemingly even 2FA was ok, but then it failed with the error in my original message.

**Comment by pitpompej** [comment]
ok, that explaines the error. i have not been able to test the plugin against the co.uk site as I do not have an english amazon account. 
but if you do not mind you may help me fix all errors and find all issues to make this plugin also run with the .co.uk amazon site, do you?

**Comment by NuxRo** [comment]
Sure, what do I do?

**Comment by pitpompej** [comment]
do you have prime and unlimited or only unlimited?

**Comment by NuxRo** [comment]
No Unlimited, just Amazon Prime Music.
https://www.amazon.co.uk/gp/dmusic/promotions/PrimeMusic

Unlimited is an additional £10 a month I believe.
