### ISSUE TITLE
Fails the auth

### ISSUE THREAD

**Issue by ghost** [pitpompej/kodi_plugins#9]
Hi,

I've installed your addon on Kodi on Debian (buster)
It asks me my Amazon credentials (without 2fa, though i activated it), but then fails with the following.
I am using the german Amazon version.
Any ideas?

17:02:51.028 T:140012803827456   ERROR: GetDirectory - Error getting
17:03:24.306 T:140011974424320   ERROR: Previous line repeats 6 times.
17:03:24.306 T:140011974424320   ERROR: /home/niki/.kodi/addons/plugin.audio.prime_music/default.py:1162: UserWarning: gzip transfer encoding is experimental!
                                              br.set_handle_gzip(True)
17:03:26.144 T:140015201767360   ERROR: GetDirectory - Error getting plugin://plugin.audio.prime_music/
17:03:26.144 T:140015201767360   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.prime_music/) failed
17:03:34.446 T:140011974424320   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: decoding Unicode is not supported
                                            Traceback (most recent call last):
                                              File "/home/niki/.kodi/addons/plugin.audio.prime_music/default.py", line 1459, in <module>
                                                index()
                                              File "/home/niki/.kodi/addons/plugin.audio.prime_music/default.py", line 80, in index
                                                loginResult = login()
                                              File "/home/niki/.kodi/addons/plugin.audio.prime_music/default.py", line 1159, in login
                                                password = unicode(requestPassword(), "utf-8")
                                            TypeError: decoding Unicode is not supported
                                            -->End of Python script error report<--
17:03:34.477 T:140015201767360   ERROR: GetDirectory - Error getting plugin://plugin.audio.prime_music/
17:03:34.478 T:140015201767360   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.prime_music/) failed
17:03:37.196 T:140011974424320   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: decoding Unicode is not supported
                                            Traceback (most recent call last):
                                              File "/home/niki/.kodi/addons/plugin.audio.prime_music/default.py", line 1461, in <module>
                                                index()
                                              File "/home/niki/.kodi/addons/plugin.audio.prime_music/default.py", line 80, in index
                                                loginResult = login()
                                              File "/home/niki/.kodi/addons/plugin.audio.prime_music/default.py", line 1159, in login
                                                password = unicode(requestPassword(), "utf-8")
                                            TypeError: decoding Unicode is not supported
                                            -->End of Python script error report<--
17:03:37.244 T:140015201767360   ERROR: GetDirectory - Error getting plugin://plugin.audio.prime_music/
17:03:37.244 T:140015201767360   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.prime_music/) failed
17:03:52.546 T:140011974424320   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: decoding Unicode is not supported
                                            Traceback (most recent call last):
                                              File "/home/niki/.kodi/addons/plugin.audio.prime_music/default.py", line 1461, in <module>
                                                index()
                                              File "/home/niki/.kodi/addons/plugin.audio.prime_music/default.py", line 80, in index
                                                loginResult = login()
                                              File "/home/niki/.kodi/addons/plugin.audio.prime_music/default.py", line 1159, in login
                                                password = unicode(requestPassword(), "utf-8")
                                            TypeError: decoding Unicode is not supported
                                            -->End of Python script error report<--
17:03:52.577 T:140015201767360   ERROR: GetDirectory - Error getting plugin://plugin.audio.prime_music/
17:03:52.577 T:140015201767360   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.prime_music/) failed

**Comment by pitpompej** [comment]
Do you use some special characters in your password (e.g. öäüß)? If so could you please try to change your password so it does not contain such characters?
